// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgeP1soh-sAMfYcuQbdrMYOL5gQ7KAacU',
    appId: '1:16794939681:web:90623872e34361b3d1ce60',
    messagingSenderId: '16794939681',
    projectId: 'event-pro-b877c',
    authDomain: 'event-pro-b877c.firebaseapp.com',
    storageBucket: 'event-pro-b877c.firebasestorage.app',
    measurementId: 'G-H1X5YZJCCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ42IPXxiWx07Ib9aknMnFsNVO9F0nS3A',
    appId: '1:16794939681:android:21a7aacf0dc2505bd1ce60',
    messagingSenderId: '16794939681',
    projectId: 'event-pro-b877c',
    storageBucket: 'event-pro-b877c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpeO1eNs9HI1uo9iW4zWLsi-sH9UG72DE',
    appId: '1:16794939681:ios:8b2120efca753618d1ce60',
    messagingSenderId: '16794939681',
    projectId: 'event-pro-b877c',
    storageBucket: 'event-pro-b877c.firebasestorage.app',
    iosBundleId: 'com.example.doAnLtdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpeO1eNs9HI1uo9iW4zWLsi-sH9UG72DE',
    appId: '1:16794939681:ios:8b2120efca753618d1ce60',
    messagingSenderId: '16794939681',
    projectId: 'event-pro-b877c',
    storageBucket: 'event-pro-b877c.firebasestorage.app',
    iosBundleId: 'com.example.doAnLtdd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgeP1soh-sAMfYcuQbdrMYOL5gQ7KAacU',
    appId: '1:16794939681:web:8366abb14d95aa1ad1ce60',
    messagingSenderId: '16794939681',
    projectId: 'event-pro-b877c',
    authDomain: 'event-pro-b877c.firebaseapp.com',
    storageBucket: 'event-pro-b877c.firebasestorage.app',
    measurementId: 'G-DK4NK467TJ',
  );
}
